language: ruby
deploy:
  provider: heroku
  api_key:
    secure: T2sAIf4EzHMMz208nrgV5ZzLgEFEQJuSw82bl7G+LJJRCdp/RVwFVjFMTjVcOH8jcOLeh7Ci5p/pGEMdswIP9yhgJGZsYHW7pZSgizdegWksvpRQ2YVY9553z1/K+DVwpcwGwSvuKbl3JlQzjrNGFiqmL2NxpuNtEL9R0EssYXA=
  app: andrew-sinner-portfolio
  on:
    repo: asinner/portfolio
